from enum import Enum

class DebateType(Enum):

	FREESTYLE='FREESTYLE'
	ADVANCE='ADVANCE'
	INTERMEDIATE='INTERMEDIATE'


class TeamSides(Enum):

	SIDE=['LEFT','RIGHT']

class ParticipantsType(Enum):

	DEBATER='DEBATER'
	AUDIENCE='AUDIENCE'
	MEDIATOR='MEDIATOR'


class DebateStatus(Enum):

	UPCOMINGDEBATE='UPCOMINGDEBATE'
	PASTDEBATE='PASTDEBATE'
	SAVEDDEBATED='SAVEDDEBATE'


class VotingType(Enum):

	SCORE='SCORE'
	VOTE='VOTE'

class DocumentType(Enum):
	AVATAR='AVATAR'
	MALEHAIR='MALEHAIR'
	FEMAILHAIR='FEMALEHAIR'
	SKIN='SKIN'
	DRESS='DRESS'
	PROFILEPICTURE='PROFILEPICTURE'

class GenderType(Enum):
	MALE='MALE'
	FEMALE='FEMALE'

